baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Pangolin Software Solutions'
theme = "blowfish"
summaryLength = 20
disqusShortname = 'pangolinsoftwaresolutions'

mainSections = ["blog", "project"]
smartTOC = true
colorScheme = "neon"

[author]
name = "Pangolin"
image = "img/pangolin.svg"
headline = "Scalable, tested solutions."
links = [
    {twitter = "https://twitter.com/JacobShore19"},
    {linkedin = "https://www.linkedin.com/in/jacob-shore-86094725a"},
    {github = "https://github.com/DewofyourYouth"}
]

[params]
secondaryLogo = "img/pangolin.png"

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"