baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Pangolin Software Solutions'
theme = "blowfish"
summaryLength = 20

mainSections = ["blog", "project"]
smartTOC = true

[author]
name = "Pangolin"
image = "img/pangolin.svg"
headline = "Scalable, tested solutions."

[params]
secondaryLogo = "img/pangolin.png"

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"