baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Pangolin Software Solutions'
theme = "blowfish"

mainSections = ["blog"]
smartTOC = true

[author]
name = "Pangolin"
image = "img/pangolin.svg"
headline = "Scalable, tested solutions."

[params]
secondaryLogo = "img/pangolin.png"

